### ISSUE TITLE
java.util.concurrent.TimeoutException while doing http2 requests

### ISSUE THREAD

**Issue by TrickyDoodle** [Blazemeter/jmeter-http2-plugin#18]
Hi! 
During using jmeter-http2-plugin I regulary get `java.util.concurrent.TimeoutException` errors for http2 requests even in a single thread mode. 

My environment:
- Ubuntu 20.04
- Jmeter 5.4.1
- jmeter-http2-plugin v1.6.1
- alpn-boot-8.1.13.v20181017.jar

Full error:
```
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Connection.awaitResponses(HTTP2Connection.java:171)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Request.sample(HTTP2Request.java:219)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Request.sample(HTTP2Request.java:143)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Request.sample(HTTP2Request.java:119)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
	at java.lang.Thread.run(Thread.java:748)

```
Most requests are performing well, but from time to time this error occurs. I tried to user different versions of jdk, but result is still the same. On the server side I don't see any corresponding errors. Any advice is welcome. 

Best regards.

**Comment by 3dgiordano** [comment]
Hi @TrickyDoodle 

I made a pre-release with some changes in the plugin.
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.2

This pre-release solve some problems in the thread management of the internal jetty http client.
Maybe you can try the pre-release and let us know if it has improved and solved the problem.

Thanks.

**Comment by RicardoPoleo** [comment]
Hello @TrickyDoodle,

It has been a while since we saw some activity regarding this issue. I'll be closing it but, if the error persists in the current version, please don't hesitate to open it up again.

Best Regards,
