### ISSUE TITLE
bzm Parallel Controller with HTTP Request

### ISSUE THREAD

**Issue by gudipudipradeep** [Blazemeter/jmeter-http2-plugin#44]
`2023-04-07 17:07:26,470 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2023-04-07 17:07:26,472 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Parallel Controller'.
java.lang.reflect.InaccessibleObjectException: Unable to make field java.lang.ThreadLocal$ThreadLocalMap java.lang.Thread.inheritableThreadLocals accessible: module java.base does not "opens java.lang" to unnamed module @358ee631
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
	at com.blazemeter.jmeter.controller.ParallelSampler$ParallelThreadFactory.cleanThreadContext(ParallelSampler.java:387) ~[jmeter-parallel-0.11.jar:?]
	at com.blazemeter.jmeter.controller.ParallelSampler$ParallelThreadFactory.newThread(ParallelSampler.java:374) ~[jmeter-parallel-0.11.jar:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:630) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at com.blazemeter.jmeter.controller.ParallelSampler.sample(ParallelSampler.java:87) ~[jmeter-parallel-0.11.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-04-07 17:07:26,474 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2023-04-07 17:07:26,475 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2023-04-07 17:07:26,475 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2023-04-07 17:07:26,475 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
`
HTTP Request working when integrated with bzm controller getting this issue.
![image](https://user-images.githubusercontent.com/8638634/230603320-b9b69771-b8ef-49b8-bab7-ec3feb4f99f0.png)

**Comment by 3dgiordano** [comment]
Hi @gudipudipradeep 

What version of JMeter are you using?
What version of java?

The error is a reflection error in Parallel Controller, not in http2.
Suppose if you are using Java 9 or later, when you instantiate jmeter.bat or jmeter.sh, jmeter detects the java version and specifies to allow reflection on all java.base/java.lang modules.
The error 'module java.base does not "opens java.lang" to unnamed module' indicates that possibly the argument "--add-opens=java.base/java.lang=ALL-UNNAMED" is not being used.
Modern JMeters will incorporate it, so it appears that you are not starting jmeter from jmeter.bat or jmeter.sh

Is it possible that you are starting jmeter not using the jmeter shell script?

**Comment by 3dgiordano** [comment]
Hi @gudipudipradeep

The issue is closed due to lack of response and inactivity.
If the proposed solution was not correct or the problem persists, you can reopen the issue or create a new one.

Thank you
